"""Image to G-code converter for LaserMac.

Converts raster images (PNG/JPG/BMP) to G-code for laser engraving.
Supports multiple dithering modes: threshold, Floyd-Steinberg, and grayscale lines.
"""

from __future__ import annotations

import numpy as np
from PIL import Image


def image_to_gcode(
    image_path: str,
    width_mm: float = 100.0,
    height_mm: float | None = None,
    dpi: int = 10,
    mode: str = "threshold",
    speed: int = 3000,
    power_max: int = 1000,
    threshold: int = 128,
) -> str:
    """Convert an image to G-code for laser engraving.

    Args:
        image_path: Path to image file.
        width_mm: Output width in mm.
        height_mm: Output height in mm (auto-calculated from aspect ratio if None).
        dpi: Lines per mm (resolution).
        mode: Dithering mode — "threshold", "floyd", or "grayscale".
        speed: Engraving speed in mm/min.
        power_max: Maximum laser power (S value, typically 0–1000).
        threshold: Brightness threshold for "threshold" mode (0–255).

    Returns:
        G-code string.
    """
    img = Image.open(image_path).convert("L")

    # Calculate dimensions
    orig_w, orig_h = img.size
    if height_mm is None:
        height_mm = width_mm * (orig_h / orig_w)

    # Resize to match desired resolution
    pixel_w = int(width_mm * dpi)
    pixel_h = int(height_mm * dpi)
    img = img.resize((pixel_w, pixel_h), Image.Resampling.LANCZOS)

    pixels = np.array(img, dtype=np.float64)

    # Apply dithering / processing
    if mode == "floyd":
        pixels = _floyd_steinberg(pixels)
    elif mode == "threshold":
        pixels = (pixels < threshold).astype(np.float64) * 255
    elif mode == "grayscale":
        pass  # Use raw grayscale values
    else:
        raise ValueError(f"Unknown mode: {mode}. Use 'threshold', 'floyd', or 'grayscale'.")

    # Generate G-code
    return _pixels_to_gcode(pixels, width_mm, height_mm, speed, power_max, mode)


def _floyd_steinberg(pixels: np.ndarray) -> np.ndarray:
    """Apply Floyd-Steinberg dithering."""
    h, w = pixels.shape
    result = pixels.copy()

    for y in range(h):
        for x in range(w):
            old_val = result[y, x]
            new_val = 255.0 if old_val > 127 else 0.0
            result[y, x] = new_val
            error = old_val - new_val

            if x + 1 < w:
                result[y, x + 1] += error * 7 / 16
            if y + 1 < h:
                if x - 1 >= 0:
                    result[y + 1, x - 1] += error * 3 / 16
                result[y + 1, x] += error * 5 / 16
                if x + 1 < w:
                    result[y + 1, x + 1] += error * 1 / 16

    return (result < 128).astype(np.float64) * 255


def _pixels_to_gcode(
    pixels: np.ndarray,
    width_mm: float,
    height_mm: float,
    speed: int,
    power_max: int,
    mode: str,
) -> str:
    """Convert pixel array to G-code using line-by-line raster scanning."""
    h, w = pixels.shape
    pixel_size_x = width_mm / w
    pixel_size_y = height_mm / h

    lines: list[str] = []
    lines.append("; Generated by LaserMac")
    lines.append(f"; Image size: {width_mm:.1f} x {height_mm:.1f} mm")
    lines.append(f"; Resolution: {w} x {h} px")
    lines.append(f"; Mode: {mode}")
    lines.append("G90 ; Absolute positioning")
    lines.append("G21 ; Millimeters")
    lines.append("M5 S0 ; Laser off")
    lines.append("")

    for row in range(h):
        y = row * pixel_size_y
        # Bi-directional scanning (zigzag)
        if row % 2 == 0:
            x_range = range(w)
        else:
            x_range = range(w - 1, -1, -1)

        # Move to start of line
        start_x = 0.0 if row % 2 == 0 else (w - 1) * pixel_size_x
        lines.append(f"G0 X{start_x:.3f} Y{y:.3f} S0")

        for col in x_range:
            x = col * pixel_size_x
            val = pixels[row, col]

            if mode == "grayscale":
                # Map grayscale: dark = high power, light = low power
                power = int((1.0 - val / 255.0) * power_max)
            else:
                # Binary: pixel is on (dark) or off
                power = power_max if val > 0 else 0

            if power > 0:
                lines.append(f"G1 X{x:.3f} Y{y:.3f} S{power} F{speed}")
            else:
                lines.append(f"G0 X{x:.3f} Y{y:.3f} S0")

    lines.append("")
    lines.append("M5 S0 ; Laser off")
    lines.append("G0 X0 Y0 ; Return to origin")
    lines.append("")
    return "\n".join(lines)


def calculate_output_size(
    image_path: str,
    width_mm: float = 100.0,
    height_mm: float | None = None,
) -> tuple[float, float]:
    """Calculate output size in mm for a given image."""
    img = Image.open(image_path)
    orig_w, orig_h = img.size
    if height_mm is None:
        height_mm = width_mm * (orig_h / orig_w)
    return (width_mm, height_mm)
