"""SVG to G-code converter for LaserMac.

Converts SVG vector paths to G-code for laser cutting/engraving.
Uses svgpathtools for path parsing and interpolation.
"""

from __future__ import annotations

from svgpathtools import svg2paths2


def svg_to_gcode(
    svg_path: str,
    scale: float = 1.0,
    speed: int = 1000,
    power: int = 1000,
    passes: int = 1,
    tolerance: float = 0.1,
) -> str:
    """Convert an SVG file to G-code.

    Args:
        svg_path: Path to SVG file.
        scale: Scale factor (1.0 = original size, assumes SVG units ~ mm).
        speed: Feed rate in mm/min.
        power: Laser power (S value).
        passes: Number of passes per path.
        tolerance: Curve interpolation tolerance in mm.

    Returns:
        G-code string.
    """
    paths, attributes, svg_attrs = svg2paths2(svg_path)

    lines: list[str] = []
    lines.append("; Generated by LaserMac — SVG vector cut")
    lines.append(f"; Source: {svg_path}")
    lines.append("G90 ; Absolute positioning")
    lines.append("G21 ; Millimeters")
    lines.append("M5 S0 ; Laser off")
    lines.append("")

    for _pass in range(passes):
        if passes > 1:
            lines.append(f"; Pass {_pass + 1}/{passes}")

        for path in paths:
            if len(path) == 0:
                continue

            # Move to start point (laser off)
            start = path.point(0)
            sx = start.real * scale
            sy = start.imag * scale
            lines.append(f"G0 X{sx:.3f} Y{sy:.3f} S0")
            lines.append(f"M3 S{power} ; Laser on")

            # Interpolate path
            path_length = path.length()
            if path_length == 0:
                continue

            num_points = max(int(path_length / tolerance), 2)

            for i in range(1, num_points + 1):
                t = i / num_points
                pt = path.point(t)
                px = pt.real * scale
                py = pt.imag * scale
                lines.append(f"G1 X{px:.3f} Y{py:.3f} F{speed}")

            lines.append("M5 S0 ; Laser off")
            lines.append("")

    lines.append("G0 X0 Y0 ; Return to origin")
    lines.append("")
    return "\n".join(lines)
